feat: add msgIdToStrFn option
ChainSafe/js-libp2p-gossipsub pull request #270
Opened 2022-06-08 08:05 UTC by tuyennhv

**Motivation**
- Lodestar would like to use `Buffer.from` to convert Uint8Array message id to string as it's more efficient as found in https://github.com/ChainSafe/lodestar/issues/3446

**Description**
- Provide `msgIdToStrFn` option so that application can provide its own implementation
- Closes #269

2022-06-08 08:27 UTC, mpetrunic commented
isn't this feature?

2022-06-08 14:31 UTC, wemeetagain requested changes
Structure lgtm

2022-06-09 17:38 UTC, dapplion commented on src/message-cache.ts
> +    msgIdToStrFn: MsgIdToStrFn,
Why put this option in the middle? Feels better as last parameter

2022-06-10 08:21 UTC, dapplion commented
Is it better to inject Buffer.from at Lodestar level or we can make assumptions here? I would imagine that anyone using gossipsub at NodeJS would benefit from such a change. @mpetrunic @wemeetagain is it a problem to multiplex NodeJS / browser code at the library level?

2022-06-10 08:35 UTC, mpetrunic commented
> Is it better to inject Buffer.from at Lodestar level or we can make assumptions here? I would imagine that anyone using gossipsub at NodeJS would benefit from such a change. @mpetrunic @wemeetagain is it a problem to multiplex NodeJS / browser code at the library level?

Generally, we can, but afaik whatever you do, if somebody uses webpack 5 will have to add buffer polyfill (or at least disable it manually). I don't imagine other users need that optimization, so it might be better to just pass the function on the lodestar level.

2022-06-10 10:37 UTC, dapplion approved these changes

2022-06-12 13:58 UTC, wemeetagain approved these changes

2022-06-13 01:13 UTC, merged